#!/bin/sh

# Initialize default values.
port=8888
DATA_ROOT="/usr/local/share/judo"
JUDO_CONFIG_HOME="$HOME/.config/judo"
project_name=$(basename $PWD | tr '[:upper:]' '[:lower:]')

case $1 in
    init)
        source $DATA_ROOT/src/init.sh
        shift 1
        exec_init "$@"
        ;;

    plugins)
        source $DATA_ROOT/src/plugins.sh
        shift 1
        exec_plugins "$@"
        ;;

    run)
        docker run --pull never -e GRANT_SUDO=yes --user=root -it --rm -p $port:8888 -v $PWD:/home/jovyan/work --name $project_name $project_name
        ;;

    help|*)
        source $DATA_ROOT/src/common.sh
        show_help judo "Create an isolated jupyter instance for development." \
            init "Initialize the Docker runtime and git repository." \
            run "Run the Docker container." \
            plugins "Manage and get information on active and installed plugins." \
            help "View this help."
        ;;
esac
